# Database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App


jwt.secret=jerseyshop_super_secret_key_2024_make_it_long
jwt.expiration=86400000

spring.mvc.pathmatch.use-suffix-pattern=false